title: kellyandbrian.info
url: https://kellyandbrian.info

plugins:
 - jekyll-relative-links
 - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

img_widths:
    - 500
    - 1000
    - 1500
    - 2000
    - 2500
    - 3000
